# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    build_test.yml                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: shtanemu <shtanemu@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/02 14:39:41 by shtanemu          #+#    #+#              #
#    Updated: 2024/01/29 15:38:41 by shtanemu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: Build Test

on:
  pull_request:
    branches:
      - '*'
    workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install build-essential
        run: sudo apt-get update && sudo apt-get install build-essential libbsd-dev -y

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: make debug
