name: Integration Test

on:
  pull_request:
    branches:
      - '*'
    workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install build-essential
        run: sudo apt-get update && sudo apt-get install build-essential libbsd-dev -y

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: make

      - name: Run test
        run: python3 test.py